version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: accounts_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  accounts:
    build: ./accounts
    ports:
      - "5001:5000"
    environment:
      - POSTGRES_DB=accounts_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    depends_on:
      - db
