version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: accounts_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
      
  accounts:
    build: ./accounts
    ports:
      - "5001:5000"
    environment:
      - POSTGRES_DB=accounts_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    depends_on:
      - db

  hospitals:
    build: ./hospitals
    ports:
      - "5002:5000"
    environment:
      - POSTGRES_DB=hospitals_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    depends_on:
      - db

  timetable:
    build: ./timetable
    ports:
      - "5003:5000"
    environment:
      - POSTGRES_DB=timetable_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    depends_on:
      - db
      - hospitals
      - accounts

  documents:
    build: ./documents
    ports:
      - "5004:5000"
    environment:
      - POSTGRES_DB=documents_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    depends_on:
      - db
      - hospitals
      - accounts
