version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: accounts_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  accounts:
    build: ./accounts
    ports:
      - "5001:5000"
    environment:
      - POSTGRES_DB=accounts_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy

  hospitals:
    build: ./hospitals
    ports:
      - "5002:5000"
    environment:
      - POSTGRES_DB=hospitals_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy

  timetable:
    build: ./timetable
    ports:
      - "5003:5000"
    environment:
      - POSTGRES_DB=timetable_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy
      hospitals:
        condition: service_started
      accounts:
        condition: service_started

  documents:
    build: ./documents
    ports:
      - "5004:5000"
    environment:
      - POSTGRES_DB=documents_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy
      hospitals:
        condition: service_started
      accounts:
        condition: service_started
